name: WinGet Setup

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Install winget
        run: |
          Invoke-WebRequest -Uri https://aka.ms/get-winget -OutFile winget.msix
          Add-AppxPackage .\winget.msix    - name: Winget test
          
      - name: Test Winget
        run: winget list --accept-source-agreements
