name: Run Stampinf Manually

on:
  workflow_dispatch:

jobs:
  test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        wget_release_id: latest

    - name: Install wingetcreate
      run: winget install wingetcreate --disable-interactivity --accept-source-agreements
