name: Run Stampinf Manually

on:
  workflow_dispatch:

jobs:
  stampinf_job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install Windows Driver Kit (WDK)
        run: |
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2128854" -OutFile "winsdksetup.exe"
          Start-Process -FilePath "winsdksetup.exe" -ArgumentList "/features OptionId.WindowsDesktopDebuggers OptionId.WindowsDesktopDevelopmentTools OptionId.WindowsDevelopmentTools /quiet /norestart" -NoNewWindow -Wait
        shell: powershell

      - name: Verify Stampinf Installation
        run: |
          $wdkPath = "C:\Program Files (x86)\Windows Kits\10\bin\x64"
          if (Test-Path "$wdkPath\stampinf.exe") {
            Write-Host "Stampinf installed successfully."
          } else {
            Write-Host "Stampinf not found!"
            exit 1
          }
        shell: powershell

      - name: Run Stampinf
        run: |
          $wdkPath = "C:\Program Files (x86)\Windows Kits\10\bin\x64"
          & "$wdkPath\stampinf.exe" -f path\to\your.inf -d "YourCompany" -c "YourCatalog.cat"
        shell: powershell
