name: Run Stampinf Manually

on:
  workflow_dispatch:

jobs:
  stampinf_job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install winget via PowerShell script
        run: |
          # Check if winget is already installed
          if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
            Write-Host "winget is not installed. Installing now..."
            # Download and install the App Installer
            Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile "appinstaller.appx"
            Add-AppxPackage -Path "appinstaller.appx"
            Write-Host "winget installation complete."
          } else {
            Write-Host "winget is already installed."
          }
        shell: powershell

      - name: Install Visual Studio 2022 and Required Workloads
        run: |
          # Download Visual Studio 2022 with required components using winget and the wdk.vsconfig file
          winget install --source winget --exact --id Microsoft.VisualStudio.2022.Community --override "--passive --config ./wdk.vsconfig"
        shell: powershell

      - name: Install Windows Driver Kit (WDK) using winget
        run: |
          winget install --source winget --exact --id Microsoft.WindowsWDK.10.0.26100 --log $env:USERPROFILE/Desktop/wdk-install.log
        shell: powershell

      - name: Verify Stampinf Installation
        run: |
          $wdkPath = "C:\Program Files (x86)\Windows Kits\10\bin\x64"
          if (Test-Path "$wdkPath\stampinf.exe") {
            Write-Host "Stampinf installed successfully."
          } else {
            Write-Host "Stampinf not found!"
            exit 1
          }
        shell: powershell

      - name: Run Stampinf
        run: |
          $wdkPath = "C:\Program Files (x86)\Windows Kits\10\bin\x64"
          & "$wdkPath\stampinf.exe" -f path\to\your.inf -d "YourCompany" -c "YourCatalog.cat"
        shell: powershell
